BEGIN;
DROP TRIGGER IF EXISTS phase12_pack_events_immutable_update;
DROP TRIGGER IF EXISTS phase12_pack_events_immutable_delete;
DROP TRIGGER IF EXISTS phase12_commands_immutable_update;
DROP TRIGGER IF EXISTS phase12_commands_immutable_delete;
DROP TRIGGER IF EXISTS phase12_verifications_immutable_update;
DROP TRIGGER IF EXISTS phase12_verifications_immutable_delete;
DROP TRIGGER IF EXISTS phase12_actuator_attempts_immutable_update;
DROP TRIGGER IF EXISTS phase12_actuator_attempts_immutable_delete;
DROP TRIGGER IF EXISTS phase12_stops_immutable_update;
DROP TRIGGER IF EXISTS phase12_stops_immutable_delete;
DROP TABLE IF EXISTS phase12_communication_states;
DROP TABLE IF EXISTS phase12_simulation_state;
DROP TABLE IF EXISTS phase12_simulated_verifications;
DROP TABLE IF EXISTS phase12_safety_stops;
DROP TABLE IF EXISTS phase12_controller_decisions;
DROP TABLE IF EXISTS phase12_actuator_attempts;
DROP TABLE IF EXISTS phase12_actuator_commands;
DROP TABLE IF EXISTS phase12_embodiment_intents;
DROP TABLE IF EXISTS phase12_replays;
DROP TABLE IF EXISTS phase12_pack_events;
DROP TABLE IF EXISTS phase12_pack_versions;
DROP TABLE IF EXISTS phase12_installed_packs;
COMMIT;
