"""Shared cognition contracts and truthful Phase 0 action runtime."""

from .actions import ActionError, ActionLedger, ActionRuntime, ExecutionOutcome
from .flags import PHASE_FEATURE_FLAGS, phase_enabled
from .lifecycle import (
    LEGAL_TRANSITIONS,
    ActionErrorCode,
    ActionState,
    IllegalActionTransition,
)
from .models import (
    ActionAttempt,
    ActionProposal,
    Authorization,
    Belief,
    CognitionContract,
    Commitment,
    ContractCompatibilityError,
    ContractError,
    ContractMigrationError,
    ContractStore,
    DecisionReceipt,
    Episode,
    Goal,
    LearningCandidate,
    Observation,
    Plan,
    Prediction,
    Situation,
    UnsupportedSchemaVersion,
    Verification,
    restore_database,
)
from .store import ActionRecord, CognitionStore

__all__ = [
    "ActionAttempt",
    "ActionError",
    "ActionErrorCode",
    "ActionLedger",
    "ActionProposal",
    "ActionRecord",
    "ActionRuntime",
    "ActionState",
    "Authorization",
    "Belief",
    "CognitionContract",
    "CognitionStore",
    "Commitment",
    "ContractCompatibilityError",
    "ContractError",
    "ContractMigrationError",
    "ContractStore",
    "DecisionReceipt",
    "Episode",
    "ExecutionOutcome",
    "Goal",
    "IllegalActionTransition",
    "LearningCandidate",
    "Observation",
    "Plan",
    "Prediction",
    "Situation",
    "UnsupportedSchemaVersion",
    "Verification",
    "PHASE_FEATURE_FLAGS",
    "phase_enabled",
    "LEGAL_TRANSITIONS",
    "restore_database",
]
